### ISSUE TITLE
Abracadabra code

### ISSUE THREAD

**Issue by m0t0rh34d** [peet86/cart-localstorage#19]
How can I read this code? Why it looks like a complete abracadabra?

**Comment by peet86** [comment]
Because I wanted to have some fun and experiment with one liners and short hands. ;) 
I didn't expect that people will start to use it.. 

Anyway I will convert the codebase to a more readable one because this kind of "fun" is not sustainable when others request features and want to contribute.. 

Until that tests and learning some shorthand js syntax might help you.. ;)
